parameters:
    prime.ez_sitemap.default.sitemap.domain: ''
    prime.ez_sitemap.default.sitemap.protocol: 'https'
    prime.ez_sitemap.default.sitemap.sitemaps_index_path: 'sitemaps'
    prime.ez_sitemap.default.sitemap.shared_max_age: 3600
    prime.ez_sitemap.default.sitemap.content_type_list:
        - ng_article
        - ng_feedback_form
        - ng_frontpage
        - ng_landing_page
    prime.ez_sitemap.default.sitemap.max_items_per_sitemap: 500
    prime.ez_sitemap.default.sitemap.excluded_nodes: ~
