services:
    prime.ez_sitemap.command.generate_sitemap:
        class: Prime\Bundle\EzSiteMapBundle\Command\GenerateSitemapCommand
        arguments:
            - '@ezpublish.config.resolver'
            - '@netgen.ezplatform_site.filter_service'
            - '@ezpublish.api.service.url_alias'
            - '%prime.ez_sitemap.default.sitemap.domain%'
            - '%prime.ez_sitemap.default.sitemap.content_type_list%'
            - '%prime.ez_sitemap.default.sitemap.max_items_per_sitemap%'
            - '%webroot_dir%'
        tags:
            -  { name: console.command }

    prime.ez_sitemap.factory:
        class: Prime\EzSiteMap\Factory\SitemapFactory
        arguments:
            - '%prime.ez_sitemap.default.sitemap.domain%'
            - '%prime.ez_sitemap.default.sitemap.protocol%'
            - '%prime.ez_sitemap.default.sitemap.sitemaps%'

    prime.ez_sitemap.controller.sitemap:
        class: Prime\Bundle\EzSiteMapBundle\Controller\SitemapController
        parent: netgen.ezplatform_site.controller.base
        arguments:
            - '@ezpublish.config.resolver'
            - '@prime.ez_sitemap.factory'
            - '%webroot_dir%'

