services:
    prime.ez_sitemap.command.generate_sitemap:
        class: Prime\Bundle\EzSiteMapBundle\Command\GenerateSitemapCommand
        arguments:
            - '@ezpublish.query_type.registry'
            - '@netgen.ezplatform_site.core.site'
            - '@ezpublish.api.service.url_alias'
            - '@prime.ez_sitemap.configuration'
            - '%webroot_dir%'
        tags:
            -  { name: console.command }

    prime.ez_sitemap.factory:
        class: Prime\EzSiteMap\Factory\SitemapFactory
        arguments:
            - '%prime.ez_sitemap.default.sitemap.domain%'
            - '%prime.ez_sitemap.default.sitemap.protocol%'
            - '%prime.ez_sitemap.default.sitemap.sitemaps_index_path%'

    prime.ez_sitemap.controller.sitemap:
        class: Prime\Bundle\EzSiteMapBundle\Controller\SitemapController
        parent: netgen.ezplatform_site.controller.base
        arguments:
            - '@ezpublish.config.resolver'
            - '@prime.ez_sitemap.factory'
            - '%webroot_dir%'

    prime.ez_sitemap.configuration:
        class: Prime\EzSiteMap\Sitemap\Configuration
        arguments:
            - '@ezpublish.config.resolver'
